# 进入服务器时的发送延迟
global-send-delay: 1
# 空资源包名称
empty-resource-pack-name: rank
# 匹配规则
match-rules:
  lobby:
    pack: rank
  horror-farmer:
    pack: horror-farmer
    regex: hf_.*
  under-tensai:
    pack: under-tensai
    regex: ut_[^0].*
  uhc:
    pack: uhc
    regex: uhc_.*
# 资源包
resource-packs:
  empty:
    url: https://src.yistars.net/resource-packs/Empty.zip
    hash-url: https://res.yistars.net/get_resource_pack_hash.php?resource_pack=Empty
    show-action-bar: false
  rank:
    url: https://src.yistars.net/resource-packs/Rank.zip
    hash-url: https://res.yistars.net/get_resource_pack_hash.php?resource_pack=Rank
  horror-farmer:
    url: https://src.yistars.net/resource-packs/HorrorFarmer.zip
    hash-url: https://res.yistars.net/get_resource_pack_hash.php?resource_pack=HorrorFarmer
  under-tensai:
    url: https://res.yistars.net/resource-packs/UnderTensai/UTP.zip
    hash-url: https://res.yistars.net/get_resource_pack_hash.php?dir=UnderTensai&resource_pack=UTP
    force: true
    hash: false
  uhc:
    url: https://src.yistars.net/resource-packs/UHC.zip
    hash-url: https://res.yistars.net/get_resource_pack_hash.php?resource_pack=UHC