# 进入服务器时的发送延迟
global-send-delay: 1
# 空资源包名称
empty-resource-pack-name: rank
# 匹配规则
match-rules:
  lobby:
    pack: rank
  horror-farmer:
    pack: horror-farmer
    regex: hf_.*
  under-tensai:
    pack: under-tensai
    regex: ut_[^0].*
  uhc:
    pack: uhc
    regex: uhc_.*
# 资源包
resource-packs:
  empty:
    url: https://src.yistars.net/resource-packs/Empty.zip
    show-action-bar: false
  rank:
    url: https://src.yistars.net/resource-packs/Rank.zip
  horror-farmer:
    url: https://src.yistars.net/resource-packs/HorrorFarmer.zip
  under-tensai:
    url: https://src.yistars.net/resource-packs/UTP.zip
    force: true
  uhc:
    url: https://src.yistars.net/resource-packs/UHC.zip