# 进入服务器时的发送延迟
global-send-delay: 20
# 空资源包名称
empty-resource-pack-name: empty
# 匹配规则
match-rules:
  lobby:
    pack: rank
  horror-farmer:
    pack: horror-farmer
    regex: hf_.*
  under-tensai:
    pack: under-tensai
    regex: ut_[^0].*
  uhc:
    pack: uhc
    regex: uhc_.*
# 资源包
resource-packs:
  empty:
    url: https://io.ivampiresp.com/d/BingTang-Server/resourcepacks/empty/Empty.zip
    show-action-bar: false
  rank:
    url: https://io.ivampiresp.com/d/BingTang-Server/resourcepacks/rank/Rank.zip
    force: true
  horror-farmer:
    url: https://io.ivampiresp.com/d/BingTang-Server/resourcepacks/horrorfarmer/HorrorFarmer.zip
  under-tensai:
    url: https://io.ivampiresp.com/d/BingTang-Server/resourcepacks/undertensai/UTP.zip
    force: true
  uhc:
    url: https://io.ivampiresp.com/d/BingTang-Server/resourcepacks/uhc/UHC.zip